name: CI

on:
  push:
    paths:
      - "**.zig"
  pull_request:
    paths:
      - "**.zig"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - run: zig version
      - run: zig env

      - name: Run Tests
        run: zig test tres.zig
